"""Per-agent renderers — one canonical body, many file formats.

Each :class:`AgentTarget` turns an :class:`~fincli.agents.content.AgentContent`
into a :class:`GeneratedFile`. Files fully owned by Fin (the Claude skill, the
Cursor rule) are written whole; files a project may already maintain by hand
(``AGENTS.md``, Copilot instructions) are marked ``managed_block`` so the
installer merges them inside fin-owned markers instead of overwriting.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

from fincli.agents.content import AgentContent

#: Provenance note embedded in every generated file.
GENERATED_NOTE = (
    "Generated by `fin agents install` — re-run it to refresh; do not edit by hand."
)


@dataclass(frozen=True)
class GeneratedFile:
    """A rendered instruction file, path relative to the project root."""

    path: str
    content: str
    #: When True, *content* is merged into any existing file inside fin-owned
    #: marker comments instead of replacing the whole file.
    managed_block: bool = False


@dataclass(frozen=True)
class AgentTarget:
    """One supported AI agent and how to render its instruction file."""

    name: str
    label: str
    path: str
    render: Callable[[AgentContent], GeneratedFile]


def _render_claude(content: AgentContent) -> GeneratedFile:
    text = (
        "---\n"
        "name: fin-commands\n"
        "description: >-\n"
        f"  {content.description}\n"
        "allowed-tools: Bash(fin:*)\n"
        "---\n"
        "\n"
        f"<!-- {GENERATED_NOTE} -->\n"
        "\n"
        "# Run project commands through Fin\n"
        "\n"
        f"{content.body}"
    )
    return GeneratedFile(path=".claude/skills/fin-commands/SKILL.md", content=text)


def _render_cursor(content: AgentContent) -> GeneratedFile:
    text = (
        "---\n"
        f'description: "{content.description}"\n'
        "alwaysApply: true\n"
        "---\n"
        "\n"
        f"<!-- {GENERATED_NOTE} -->\n"
        "\n"
        f"{content.body}"
    )
    return GeneratedFile(path=".cursor/rules/fin-commands.mdc", content=text)


def _render_agents_md(content: AgentContent) -> GeneratedFile:
    return GeneratedFile(path="AGENTS.md", content=content.body, managed_block=True)


def _render_copilot(content: AgentContent) -> GeneratedFile:
    return GeneratedFile(
        path=".github/copilot-instructions.md",
        content=content.body,
        managed_block=True,
    )


#: All supported agents, keyed by CLI name (dict order = display order).
TARGETS: dict[str, AgentTarget] = {
    "claude": AgentTarget(
        name="claude",
        label="Claude Code (skill)",
        path=".claude/skills/fin-commands/SKILL.md",
        render=_render_claude,
    ),
    "cursor": AgentTarget(
        name="cursor",
        label="Cursor (project rule)",
        path=".cursor/rules/fin-commands.mdc",
        render=_render_cursor,
    ),
    "codex": AgentTarget(
        name="codex",
        label="Codex & any AGENTS.md-aware agent",
        path="AGENTS.md",
        render=_render_agents_md,
    ),
    "copilot": AgentTarget(
        name="copilot",
        label="GitHub Copilot",
        path=".github/copilot-instructions.md",
        render=_render_copilot,
    ),
}

#: Installed when ``fin agents install`` is run with no explicit agents.
#: AGENTS.md already covers most AGENTS.md-aware tools; Copilot is opt-in.
DEFAULT_TARGETS: tuple[str, ...] = ("claude", "cursor", "codex")
