#!/usr/bin/env python3

# Custom Import
from helpers.System import System
from helpers.Application import Application
from helpers.Docker import Env, Feature
from helpers.Command import Command
from helpers.Colors import Color

system = System()
app = Application()
command = Command()

if command.getCommand() in ['up']:
    from bin.Container import Container

    method = getattr(Container(), command.getCommand())
    method(command.getActions())
else :
    system.printLn('Help')
    print('None known command given...')

system.terminate()
