#!/usr/bin/env python3

# ------------------------------------------------------

# from helpers.Docker import Asset
# from helpers.Env import Env

# print(Asset().canStartAsset('mysql'))

# raise SystemExit


# ------------------------------------------------------

# Custom Import
from helpers.Command import Command, Output
from helpers.System import System

command = Command()
output = Output()
system = System()

if command.getCommand() in ['up', 'down', 'stop']:
    from bin.Container import Container

    method = getattr(Container(), command.getCommand())
    method(command)
else:
    output.printLn('Help')
    output.printLn('None known command given...')

system.terminate()

# # # # Import dynamic Classes
# nameSpace = __import__('plugins.Laravel')
# module = getattr(nameSpace, 'Laravel')
# pluginClass = getattr(module, 'Laravel')
# method = getattr(pluginClass, 'image')