#!/usr/bin/env python3

# ------------------------------------------------------

# from helpers.Docker import Asset
# from helpers.Env import Env

# print(Asset().canStartAsset('mysql'))

# raise SystemExit


# ------------------------------------------------------

# Custom Import
from helpers.Command import Command
from helpers.System import System

command = Command()
system = System()

if command.getCommand() in ['up']:
    from bin.Container import Container

    method = getattr(Container(), command.getCommand())
    method(command.getActions())
else:
    system.printLn('Help')
    print('None known command given...')

system.terminate()
